/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedPoolPoolDisplayIdIndexRouteImport } from './routes/_protected/pool/$poolDisplayId/index'
import { Route as ProtectedPoolPoolDisplayIdSheetSheetDisplayIdRouteImport } from './routes/_protected/pool/$poolDisplayId/sheet/$sheetDisplayId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPoolPoolDisplayIdIndexRoute =
  ProtectedPoolPoolDisplayIdIndexRouteImport.update({
    id: '/pool/$poolDisplayId/',
    path: '/pool/$poolDisplayId/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPoolPoolDisplayIdSheetSheetDisplayIdRoute =
  ProtectedPoolPoolDisplayIdSheetSheetDisplayIdRouteImport.update({
    id: '/pool/$poolDisplayId/sheet/$sheetDisplayId',
    path: '/pool/$poolDisplayId/sheet/$sheetDisplayId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pool/$poolDisplayId/': typeof ProtectedPoolPoolDisplayIdIndexRoute
  '/pool/$poolDisplayId/sheet/$sheetDisplayId': typeof ProtectedPoolPoolDisplayIdSheetSheetDisplayIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/': typeof ProtectedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pool/$poolDisplayId': typeof ProtectedPoolPoolDisplayIdIndexRoute
  '/pool/$poolDisplayId/sheet/$sheetDisplayId': typeof ProtectedPoolPoolDisplayIdSheetSheetDisplayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/pool/$poolDisplayId/': typeof ProtectedPoolPoolDisplayIdIndexRoute
  '/_protected/pool/$poolDisplayId/sheet/$sheetDisplayId': typeof ProtectedPoolPoolDisplayIdSheetSheetDisplayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/api/auth/$'
    | '/pool/$poolDisplayId/'
    | '/pool/$poolDisplayId/sheet/$sheetDisplayId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/'
    | '/api/auth/$'
    | '/pool/$poolDisplayId'
    | '/pool/$poolDisplayId/sheet/$sheetDisplayId'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/signup'
    | '/_protected/'
    | '/api/auth/$'
    | '/_protected/pool/$poolDisplayId/'
    | '/_protected/pool/$poolDisplayId/sheet/$sheetDisplayId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/pool/$poolDisplayId/': {
      id: '/_protected/pool/$poolDisplayId/'
      path: '/pool/$poolDisplayId'
      fullPath: '/pool/$poolDisplayId/'
      preLoaderRoute: typeof ProtectedPoolPoolDisplayIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/pool/$poolDisplayId/sheet/$sheetDisplayId': {
      id: '/_protected/pool/$poolDisplayId/sheet/$sheetDisplayId'
      path: '/pool/$poolDisplayId/sheet/$sheetDisplayId'
      fullPath: '/pool/$poolDisplayId/sheet/$sheetDisplayId'
      preLoaderRoute: typeof ProtectedPoolPoolDisplayIdSheetSheetDisplayIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedPoolPoolDisplayIdIndexRoute: typeof ProtectedPoolPoolDisplayIdIndexRoute
  ProtectedPoolPoolDisplayIdSheetSheetDisplayIdRoute: typeof ProtectedPoolPoolDisplayIdSheetSheetDisplayIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedPoolPoolDisplayIdIndexRoute: ProtectedPoolPoolDisplayIdIndexRoute,
  ProtectedPoolPoolDisplayIdSheetSheetDisplayIdRoute:
    ProtectedPoolPoolDisplayIdSheetSheetDisplayIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
