/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface ExtConference {
  abbreviation: string | null;
  id: number;
  name: string;
  short_name: string;
}

export interface ExtTeam {
  abbreviation: string;
  conference_id: number;
  id: number;
  school: string;
}

export interface DB {
  ext_conference: ExtConference;
  ext_team: ExtTeam;
}
