/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface ExtConference {
  display_name_short: string;
  id: Generated<number>;
  slug: string;
}

export interface ExtTeam {
  conference_id: number;
  display_name: string;
  id: Generated<number>;
  slug: string;
}

export interface DB {
  ext_conference: ExtConference;
  ext_team: ExtTeam;
}
