/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface ExtConference {
  abbreviation: string;
  id: number;
  name: string;
  short_name: string;
}

export interface ExtGame {
  away_conference: string;
  away_id: number;
  conference_game: boolean;
  home_conference: string;
  home_id: number;
  id: number;
  start_date: Timestamp;
  week: number;
}

export interface ExtLine {
  away_moneyline: number | null;
  formatted_spread: string;
  game_id: number;
  home_moneyline: number | null;
  over_under: number | null;
  over_under_open: number | null;
  provider: string;
  spread: number | null;
  spread_open: number | null;
}

export interface ExtTeam {
  abbreviation: string | null;
  conference: string;
  id: number;
  logo_url: string | null;
  school: string;
}

export interface Pool {
  created_at: Generated<Timestamp>;
  display_id: Generated<string>;
  id: Generated<number>;
  name: string;
  owner_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface Sheet {
  created_at: Generated<Timestamp>;
  display_id: Generated<string>;
  id: Generated<number>;
  name: string;
  owner_id: string;
  pool_id: number;
  updated_at: Generated<Timestamp>;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  ext_conference: ExtConference;
  ext_game: ExtGame;
  ext_line: ExtLine;
  ext_team: ExtTeam;
  pool: Pool;
  session: Session;
  sheet: Sheet;
  user: User;
  verification: Verification;
}
