/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ExtConference {
  abbreviation: string;
  id: number;
  name: string;
  short_name: string;
}

export interface ExtGame {
  away_conference: string;
  away_id: number;
  conference_game: boolean;
  home_conference: string;
  home_id: number;
  id: number;
  start_date: Timestamp;
  week: number;
}

export interface ExtTeam {
  abbreviation: string | null;
  conference: string;
  id: number;
  school: string;
}

export interface DB {
  ext_conference: ExtConference;
  ext_game: ExtGame;
  ext_team: ExtTeam;
}
